export const academicStandards = [
  'ધોરણ 9', 'ધોરણ 10', '11 આર્ટસ', '11 ઉત્તર બુનિયાદી', '11 કોમર્સ', '11 સાયન્સ',
  '12 આર્ટસ', '12 ઉત્તર બુનિયાદી', '12 કોમર્સ', '12 સાયન્સ',
  'b.a sem-1', 'b.a sem-2', 'b.a sem-3', 'b.a sem-4', 'b.a sem-5', 'b.a sem-6',
  'b.com sem-1', 'b.com sem-2', 'b.com sem-3', 'b.com sem-4', 'b.com sem-5', 'b.com sem-6',
  'b.sc sem-1', 'b.sc sem-2', 'b.sc sem-3', 'b.sc sem-4', 'b.sc sem-5', 'b.sc sem-6',
  'b.b.a sem-1', 'b.b.a sem-2', 'b.b.a sem-3', 'b.b.a sem-4', 'b.b.a sem-5', 'b.b.a sem-6',
  'b.c.a sem-1', 'b.c.a sem-2', 'b.c.a sem-3', 'b.c.a sem-4', 'b.c.a sem-5', 'b.c.a sem-6',
  'brs sem-1', 'brs sem-2', 'brs sem-3', 'brs sem-4', 'brs sem-5', 'brs sem-6',
  'b.p.e.s sem-1', 'b.p.e.s sem-2', 'b.p.e.s sem-3', 'b.p.e.s sem-4', 'b.p.e.s sem-5', 'b.p.e.s sem-6',
  'l.l.b sem-1', 'l.l.b sem-2', 'l.l.b sem-3', 'l.l.b sem-4', 'l.l.b sem-5', 'l.l.b sem-6',
  'b.ed sem-1', 'b.ed sem-2', 'b.ed sem-3', 'b.ed sem-4',
  'm.ed sem-1', 'm.ed sem-2', 'm.ed sem-3', 'm.ed sem-4',
  'PTC year 1', 'PTC year 2',
  'm.a sem-1', 'm.a sem-2', 'm.a sem-3', 'm.a sem-4',
  'm.com sem-1', 'm.com sem-2', 'm.com sem-3', 'm.com sem-4',
  'm.sc sem-1', 'm.sc sem-2', 'm.sc sem-3', 'm.sc sem-4',
  'm.sc (IT) sem-1', 'm.sc (IT) sem-2', 'm.sc (IT) sem-3', 'm.sc (IT) sem-4',
  'm.b.a sem-1', 'm.b.a sem-2', 'm.b.a sem-3', 'm.b.a sem-4',
  'MCA sem-1', 'MCA sem-2', 'MCA sem-3', 'MCA sem-4',
  'm.s.w sem-1', 'm.s.w sem-2', 'm.s.w sem-3', 'm.s.w sem-4',
  'b.e sem-1', 'b.e sem-2', 'b.e sem-3', 'b.e sem-4', 'b.e sem-5', 'b.e sem-6', 'b.e sem-7', 'b.e sem-8',
  'b.tech agri sem-1', 'b.tech agri sem-2', 'b.tech agri sem-3', 'b.tech agri sem-4', 'b.tech agri sem-5', 'b.tech agri sem-6', 'b.tech agri sem-7', 'b.tech agri sem-8',
  'civil engineering', 'IT',
  'mbbs year 1', 'mbbs year 2', 'mbbs year 3', 'mbbs year 4',
  'BAMS આયુર્વેદિક year 1', 'BAMS આયુર્વેદિક year 2', 'BAMS આયુર્વેદિક year 3', 'BAMS આયુર્વેદિક year 4',
  'BHMS year 1', 'BHMS year 2', 'BHMS year 3', 'BHMS year 4',
  'વેટરનરી ડો.',
  'b.sc નર્સિંગ sem-1', 'b.sc નર્સિંગ sem-2', 'b.sc નર્સિંગ sem-3', 'b.sc નર્સિંગ sem-4', 'b.sc નર્સિંગ sem-5', 'b.sc નર્સિંગ sem-6', 'b.sc નર્સિંગ sem-7', 'b.sc નર્સિંગ sem-8',
  'GNM year 1', 'GNM year 2', 'GNM year 3',
  'ANM year 1', 'ANM year 2',
  'b.pharm sem-1', 'b.pharm sem-2', 'b.pharm sem-3', 'b.pharm sem-4', 'b.pharm sem-5', 'b.pharm sem-6', 'b.pharm sem-7', 'b.pharm sem-8',
  'd.pharm year-1', 'd.pharm year-2',
  'b.optometry', 'PGDMLT', 'X-RAY TEC',
  'diplo civil eng sem-1', 'diplo civil eng sem-2', 'diplo civil eng sem-3', 'diplo civil eng sem-4', 'diplo civil eng sem-5', 'diplo civil eng sem-6',
  'diplo it sem-1', 'diplo it sem-2', 'diplo it sem-3', 'diplo it sem-4', 'diplo it sem-5', 'diplo it sem-6',
  'diplo eng sem-1', 'diplo eng sem-2', 'diplo eng sem-3', 'diplo eng sem-4', 'diplo eng sem-5', 'diplo eng sem-6',
  'diplo chemi eng', 'diplo naturotherapy', 'diplo painting', 'diplo pg', 'diplo ફાર્મસી',
  'ITI mechanic', 'ITI mechanic (diesel)', 'ITI copa', 'ITI com ope', 'ITI ઇલેક્ટ્રિકલ', 'ITI ફિટર',
  'si sem-1', 'si sem-2',
  'gujcet', 'neet', 'JEE', 'UGC-NET',
  'Phd', 'B.Tech', 'ડિપ્લો ફાયરમેન', 'B.P.Ed', 'G.D.C.A', 'L.L.M', 'diplo Agriculture'
];
